import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

export default function Home({}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Peyton Gardipee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 style={{ width: "100%", textAlign: "center" }}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
}
